<a href="https://colab.research.google.com/github/dubeyshubham786/66daysofdata/blob/main/Day_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Numpy***

Numpy stands for Numerical Python.

We use numpy library because


1.   It is faster
2.   Easy to use
3.   Use less memory



 

In [2]:
# Importing numpy array as np

import numpy as np

In [5]:
# Creating a numpy array

array = np.array([1, 2, 3, 4])

In [6]:
array 

array([1, 2, 3, 4])

In [12]:
# above is a single dimensional array object
# Creating two dimension array in numpy 

arr = np.array([['a' ,'b', 'c'], ['x', 'y', 'z']])

In [13]:
arr

array([['a', 'b', 'c'],
       ['x', 'y', 'z']], dtype='<U1')

In [15]:
# We can see the dimensions of an array by ndim method

arr.ndim

2

In [16]:
# The shape of a numpy array can be seen by shape method

arr.shape

(2, 3)

In [19]:
# Size and datatype od an array can be found by using size and dtype function

print(arr.dtype)
print(arr.size)

<U1
6


## **Creating a numpy array**

There are several method of creating numpy arrays. Like we can create numpy array with the help of list or tuples. 

In [20]:
# creating a numpy array with the help of list

a = np.array([[1,3,5], [2,4,6]])

In [22]:
print(a)

[[1 3 5]
 [2 4 6]]


In [37]:
# Creating a numpy array with the help of tuple

b = np.array((1, 2, 3, 4, 5))

In [38]:
print(b)

[1 2 3 4 5]


In [39]:
b.dtype

dtype('int64')

In [42]:
# Creating array with all zeroes
# We are creating 3 by 4 matrix array

c = np.zeros((3,4))

In [43]:
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [53]:
# We can also create array with the help of full method.
# Full method is used to create an array that is of the same number

d = np.full((3, 3), 5)

In [54]:
print(d)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [55]:
# We can also change the datatype of this array with the help of dtype function

d1 = np.full((3,3), 5, dtype='complex')

In [56]:
print(d1)

[[5.+0.j 5.+0.j 5.+0.j]
 [5.+0.j 5.+0.j 5.+0.j]
 [5.+0.j 5.+0.j 5.+0.j]]


In [57]:
# Using random function for creating an array
# This function will create an array with random values

np.random.random((3,3))

array([[0.79138663, 0.51226185, 0.3253195 ],
       [0.09227059, 0.55457664, 0.5630983 ],
       [0.13678631, 0.49630491, 0.86316131]])

In [59]:
# arange function can also be used to create an array in sequence of numbers
# For this first we will need to insert the range of the numbers and then the step size of the number

e = np.arange(0, 30, 5)

In [60]:
print(e)

[ 0  5 10 15 20 25]


In [61]:
# We can also use linspace function for creating an array with between the range of values
# having equal space between them. 
# First we will insert a range of numbers and then the number values that we want.

g = np.linspace(0, 5, 10)

In [62]:
g

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [63]:
# We can also reshape an array provided that the original size of array remains same

arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
  
newarr = arr.reshape(2, 2, 3)

In [64]:
newarr

array([[[1, 2, 3],
        [4, 5, 2]],

       [[4, 2, 1],
        [2, 0, 1]]])

In [65]:
print(arr.size)

12


In [66]:
print(newarr.size)

12


In [68]:
# If we want to get an array into one dimension then we can use the flatten method

print(newarr.flatten())

[1 2 3 4 5 2 4 2 1 2 0 1]


## **Array Indexing and Slicing**

Indexing in numpy is similar to list.

The slicing syntax can be defined like this [row:column:step]

If step is not provided than we will take it as zero.

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [69]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [71]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


## **Transpose of an array**

We can get the transpose of an array by using the following operation.

```
# This is formatted as code
```





In [73]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [75]:
# Now to get the transpose of it we can do like this

print(arr.T)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


## **Universal functions (ufunc)**

NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.

In [81]:
# We can get array of sine values

a = np.array([0, np.pi/2, np.pi])

In [82]:
print(a)

[0.         1.57079633 3.14159265]


In [80]:
# The sin values of this array is

print(np.sin(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [78]:
print(sin_arr)

[0.         1.57079633 3.14159265]


In [83]:
# We can also create exponential values of an array by np.exp() function
# creating a one dimensional array

a = np.array([0, 1, 2])

In [84]:
print(np.exp(a))
# it is e to the power of the elements of an array a

[1.         2.71828183 7.3890561 ]


In [85]:
# Similarly for creating a square root we can use np.sqrt

print(np.sqrt(a))

[0.         1.         1.41421356]


## **Sorting Array**

We can sort array by using np.sort() method in python.

In [87]:
# Lets take 3 dimensional that we wish to sort

a = np.array([[1, 4, 2], [3, 4, 6],[0, -1, 5]])

In [88]:
# Sorting the above array with axis= none
# Axis=None means that it will sort all the elements in the ascending order

np.sort(a, axis = None)

array([-1,  0,  1,  2,  3,  4,  4,  5,  6])

In [89]:
# For sorting column wise we will put axis=0
# Take one column and arrange it in ascending order
# Similarly for another column and so on.

np.sort(a, axis=0)

array([[ 0, -1,  2],
       [ 1,  4,  5],
       [ 3,  4,  6]])

In [90]:
# For sorting row wise we will put axis=1
# Here it will take one row and sort all the elements of that row in ascending order
# Similarly for another rows and so on

np.sort(a, axis=1)

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

## **Stacking of Numpy Array**

Numpy array can be merged into following different types.


1.   Vertical Stacking
2.   Horizontal Stacking
3.   Column stacking
4.   Concatenate stacking



In [4]:
a = np.array([[1, 2],
              [3, 4]])
  
b = np.array([[5, 6],
              [7, 8]])

In [5]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [8]:
# For vertical stacking 

print(np.vstack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [10]:
print(np.vstack((b, a)))

[[5 6]
 [7 8]
 [1 2]
 [3 4]]


In [11]:
# For Horizontal stacking

print(np.hstack((a, b)))

[[1 2 5 6]
 [3 4 7 8]]


In [12]:
print(np.hstack((b, a)))

[[5 6 1 2]
 [7 8 3 4]]


In [13]:
# For column stacking we will use

print(np.column_stack((a, b)))

[[1 2 5 6]
 [3 4 7 8]]


In [14]:
print(np.column_stack((b, a)))

[[5 6 1 2]
 [7 8 3 4]]


In [16]:
# For merging the array 

print(np.concatenate((a, b), 1))

[[1 2 5 6]
 [3 4 7 8]]


## Splitting of Numpy array

We can split numpy array into 3 types. Vertical splitting, Horizontal splitting and splitting along specified axis.

In [18]:
a = np.array([[1, 3, 5, 7, 9, 11],
              [2, 4, 6, 8, 10, 12]])

In [19]:
print(a)

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]]


In [24]:
# For Vertical splitting of an array

print(np.vsplit(a, 2))

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


In [25]:
# It will split along vertical axis into 2 parts.
# Similarly we can also split along horizontal axis into 2 parts

print(np.hsplit(a, 2))

[array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]


## **Datetime in Python**



In [27]:
# creating a date
today = np.datetime64('2017-02-12')
print("Date is:", today)
print("Year is:", np.datetime64(today, 'Y'))

Date is: 2017-02-12
Year is: 2017


## **Matrix function in Numpy**

We can do many matrix operation using numpy function. Like we can find the rank, multiply matrix, find eigen values and eigen vectors and so on. 

In [28]:
# Let us take a numpy array

A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

In [38]:
print(A)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]


In [30]:
# Now if we want to find the rank of matrix then

print(np.linalg.matrix_rank(A))

3


In [33]:
# For finding the trace of matrix

print(np.trace(A))

11


In [39]:
# If we want to raise the power of matrix

print(np.linalg.matrix_power(A, 2))

[[42 12 18]
 [26 48 29]
 [58 42 91]]


In [34]:
# For finding the determinant of a matrix

print(np.linalg.det(A))

-306.0


In [35]:
# If it's determinant is not zero then we can also find the inverse of that matrix

print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
